version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run: 
                name: Install dependencies
                command: |
                    npm i selenium-webdriver
                    sudo npm i -g http-server
            - run:
                name: Run test
                command: |
                    http-server &
                    sleep 3s
                    node .circleci/selenium.js
            - store_artifacts:
                path: test-result.html
                destination: test-result.html
                