version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run: 
                name: Install dependencies
                command: yarn global add selenium-webdriver http-server
            - run:
                name: Start http server
                command: http-server ./test
            - run:
                name: Run test
                command: node .circleci/selenium.js
            - store_artifacts:
                path: screenshot.png
                