version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: yarn
            - run:
                name: Greenkeeper
                command: sudo npm i -g greenkeeper-lockfile && greenkeeper-lockfile-update
            - run:
                name: Install karma launchers
                command: npm i karma-sauce-launcher
            - run:
                name: Run unit tests
                command: yarn test
            - run:
                name: Greenkeeper
                command: greenkeeper-lockfile-upload
            - store_test_results:
                path: junit
            - store_artifacts:
                path: coverage
                destination: coverage
