version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run: sudo apt-get install -y -qq gconf2
            - run:
                name: Run test
                command:
                    firefox file:///$(pwd)/test/index.html
