version: 2
jobs:
  checkout:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  dependencies:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint
  unit_test:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run unit tests
          command: yarn test
workflows:
  version: 2
  lint_and_test:
    jobs:
      - checkout:
          filters:
            branches:
              ignore:
                - gh-pages
      - dependencies:
          requires:
            - checkout
      - lint:
          requires:
            - dependencies
      - unit_test:
          requires:
            - dependencies
