version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - yarn-{{ checksum "yarn.lock" }}
            - run:
                name: Install dependencies
                command: yarn
            - save_cache:
                key: yarn-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
            - run:
                name: Greenkeeper
                command: sudo npm i -g greenkeeper-lockfile && greenkeeper-lockfile-update
            - run:
                name: Run unit tests
                command: yarn test
            - run:
                name: Greenkeeper
                command: greenkeeper-lockfile-upload
            - run:
                name: Report the coverage
                command: npm i codecov && codecov
            - store_test_results:
                path: junit
            - store_artifacts:
                path: coverage
                destination: coverage
