version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run: 
                name: Install dependencies
                command: yarn
            - run:
                name: Run test
                command: yarn test
            - store_artifacts:
                path: /screenshot.png
                