version: 2
jobs:
    build:
        docker:
            - image: selenium/node-firefox:latest
        steps:
            - checkout
            - run:
                name: Run test
                command:
                    firefox file:///$(pwd)/test/index.html
