version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run: npm i geckodriver
            - restore_cache:
                key: yarn-{{checksum "yarn.lock"}}
            - run: 
                name: Install dependencies
                command: yarn
            - save_cache:
                key: yarn-{{checksum "yarn.lock"}}
                paths: ~/.cache/yarn
            - run:
                name: Run test
                command: yarn test
            - store_artifacts:
                path: screenshot.png
                