version: 2
jobs:
    build:
        docker:
            - image: selenium/node-firefox:latest
        steps:
            - run: apt-get -qq update && apt-get -qq -y install git
            - checkout
            - run:
                name: Run test
                command:
                    firefox file:///$(pwd)/test/index.html
